name: Lint

on:
  push:
    branches-ignore: [master]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v3@sha256:fbc0dc25754a03828ec6cc2efddfe5fa667ac20c052a81de6c6b22c0a659ecaa
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MD: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          DEFAULT_BRANCH: master
